"""
creation of comcot.ctl given the grids and parameters on modela_tsunami.py
Based on Cifuentes-Lobos et al. (2023)
"""
import numpy as np 
import csv 



# vertical displacements to tsunami model
def crea_comcotctl(archivo_deformacion, ruta_deformacion, lista_nombre_grillas, tiempo_total=14400.000, delta_t=60.0, friccion1 = 0.013, friccion2 = 0.025, salidas_gral = 0 ):
    """

    INPUT:
    archivo_deformacion: deformation file used as input for tsunami modeling
    ruta_deformacion: path to deformation files
    lista_nombre_grilla: list of grids to be used in modeling
    id: identifier number of the deformation file being used
    tiempo_total: total simulation time in seconds
    delta_t: data saving interval in seconds
    friccion1: Manning friction value for level 2 and 3 grids
    friccion2: Manning friction value for level 4 grids
    salidas_gral: output types to save: 0: Zmax 1: time series (requires ts_locations.dat) 2: both
    """

    """
    PRELIMINARY SETUP
    """
    # deformation / vertical displacement input
    def_if = str(archivo_deformacion.split("_")[1].split(".")[0]) # name format "deformacion_n.csv", to create archivo comcot_n.ctl
    # name of ctl file for each deformation file
    nombre_archivo_ctl = "comcot_"+def_if+".ctl"

    # 
    # check on total time
    if not isinstance(tiempo_total,str):
        tiempo_total = str(tiempo_total)
    # check on delta_t:
    if not isinstance(delta_t,str):
        delta_t = str(delta_t)
    # check on friccion1:
    if not isinstance(friccion1,str):
        friccion1 = str(friccion1)
    # check on friccion2:
    if not isinstance(friccion2,str):
        friccion2 = str(friccion2)
    # check on salidas_gral:
    if not isinstance(salidas_gral,str):
        salidas_gral = str(salidas_gral)

    
    # deformation files are in .csv, we have to change it because comcot needs .xyz files
    if not ruta_deformacion.endswith("/"):
        ruta_archivo_deformacion = ruta_deformacion + "/" + archivo_deformacion
    else:
        ruta_archivo_deformacion = ruta_deformacion + archivo_deformacion
    # load file
    x,y,z = np.loadtxt(ruta_archivo_deformacion, delimiter = ",", usecols = (0,1,2), unpack = True)
    data = np.stack([x.ravel(), y.ravel(), z.ravel()],axis = 1)
    # new name for the file 
    archivo_deformacion_xyz = archivo_deformacion.replace("csv","xyz")
    # save the xyz file
    np.savetxt(archivo_deformacion_xyz,data,fmt='%2.8f')
    del x, y, z
    


    """
    comcot.ctl creation
    """
    #
    ctl = open(nombre_archivo_ctl,"a")
    ctl.write("#################################################\n")
    ctl.write("#                                               #\n")
    ctl.write("# Control file for COMCOT program (v1.7)        #\n")
    ctl.write("#                                               #\n")
    ctl.write("#################################################\n")
    ctl.write("#--+-----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8\n")
    ctl.write("#===============================================:===============================\n")
    ctl.write("# General Parameters for Simulation             : Value Field                  |\n")
    ctl.write("#===============================================:===============================\n")
    ctl.write("#Job Description: NZ30sec bathymetry, Spherical Coordinates for code testing\n")
    ctl.write("Total run time (Wall clock, seconds)           :  " + tiempo_total + "\n")
    ctl.write("Time interval to Save Data    ( unit: sec )    :  " + delta_t + "\n")
    ctl.write("Output Zmax & TS (0-Max Z;1-Timeseries;2-Both) :  " + salidas_gral + "\n")
    ctl.write("Start Type (0-Cold start; 1-Hot start)         :     0\n")
    ctl.write("Resuming Time If hot start (Seconds)           :   800.00\n")
    ctl.write("Specify Min WaterDepth offshore  (meter)       :    0.00\n")
    ctl.write("Initial Cond. (0:FLT,1:File,2:WM,3:LS,4:FLT+LS):     1\n")
    ctl.write("Specify BC  (0-Open;1-Sponge;2-Wall;3-FACTS)   :     0\n")
    ctl.write("Specify Input Z filename (for BC=3, FACTS)     : mw94_n22_nz_ha.xyt\n")
    ctl.write("Specify Input U filename (for BC=3, FACTS)     : mw94_n22_nz_ua.xyt\n")
    ctl.write("Specify Input V filename (for BC=3, FACTS)     : mw94_n22_nz_va.xyt\n")
    ctl.write("\n")
    ctl.write("#===============================================:===============================\n")
    ctl.write("# Parameters for Fault Model (Segment 01)       :Values                        |\n")
    ctl.write("#===============================================:===============================\n")
    ctl.write("No. of FLT Planes (With fault_multi.ctl if >1) :   1\n")
    ctl.write("Fault Rupture Time (seconds)                   :   0.0\n")
    ctl.write("Faulting Option (0: Model; 1- Data;)           :   1\n")
    ctl.write("Focal Depth                             (meter):   17800.000\n")
    ctl.write("Length of source area                   (meter):   208929.613\n")
    ctl.write("Width of source area                    (meter):   81658.2371\n")
    ctl.write("Dislocation of fault plate              (meter):   5.5879\n")
    ctl.write("Strike direction (theta)               (degree):   5.00\n")
    ctl.write("Dip  angle       (delta)               (degree):   22.000\n")
    ctl.write("Slip angle       (lamda)               (degree):   106.000\n")
    ctl.write("Origin of Comp. Domain (Layer 01) (Lat, degree):   -50.0\n")
    ctl.write("Origin of Comp. Domain (Layer 01) (Lon, degree):   278.004\n")
    ctl.write("Epicenter: Latitude                    (degree):   -31.22\n")
    ctl.write("Epicenter: Longitude                   (degree):   287.73\n")
    ctl.write("File Name of Deformation Data                  : " + archivo_deformacion_xyz + "\n")
    ctl.write("Data Format Option (0-COMCOT; 1-MOST; 2-XYZ)   :     2\n")
    ctl.write("\n")
    ctl.write("#===============================================:===============================\n")
    ctl.write("#  Parameters for Wave Maker                    :Values                        |\n")
    ctl.write("#===============================================:===============================\n")
    ctl.write("Wave type  ( 1:Solit, 2:given, 3:focusing )    :     1\n")
    ctl.write("FileName of Customized Input (for Type=2)      : fse.dat\n")
    ctl.write("Incident direction( 1:top,2:bt,3:lf,4:rt,5:ob ):     2\n")
    ctl.write("Characteristic Wave Amplitude        (meter)   :     0.500\n")
    ctl.write("Typical Water depth                  (meter)   :  2000.000 \n")
    ctl.write("\n")
    ctl.write("#===============================================:===============================\n")
    ctl.write("#  Parameters for Submarine LS/Transient Motion :ValUes                        |\n")
    ctl.write("#===============================================:===============================\n")
    ctl.write("X Coord. of Left/West Edge of Landlide Area    :  177.00\n")
    ctl.write("X Coord. of Right/East Edge of Landlide Area   :  179.00\n")
    ctl.write("Y Coord. of Bottom/South Edge of Landlide Area :  -41.00\n")
    ctl.write("Y Coord. of Top/North Edge of Landlide Area    :  -39.00\n")
    ctl.write("File Name of landslide Data                    : landslide_test.dat\n")
    ctl.write("Data Format Option (0-Old; 1-XYT; 2-Function)  :     2\n")
    ctl.write(" \n")
    ctl.write("#===============================================:===============================\n")
    ctl.write("# Configurations for all grids                  :Values                        |\n")
    ctl.write("#===============================================:===============================\n")
    ctl.write("# Parameters for 1st-level grid -- layer 01     :Values                        |\n")
    ctl.write("#===============================================:===============================\n")
    if "topo216v2.xyz" in lista_nombre_grillas:
        ctl.write(" Run This Layer ?       (0:Yes,       1:No     ):     0\n")
    else:
        ctl.write(" Run This Layer ?       (0:Yes,       1:No     ):     1\n")
    ctl.write(" Coordinate System    (0:spherical, 1:cartesian):     0\n")
    ctl.write(" Governing Equations  (0:linear,    1:nonlinear):     0\n")
    ctl.write(" Grid Size  (dx, sph:minute, cart:meter)        :     2.16\n")
    ctl.write(" Time step                            ( second ):     1.0\n")
    ctl.write(" Bottom Friction Switch? (0:Yes,1:No,2:var. n ) :     1\n")
    ctl.write(" Manning's Roughness Coef. (For fric.option=0)  :     " + friccion1 + "\n")
    ctl.write(" Layer Ouput Option? (0:Z+Hu+Hv;1:Z Only;2:NONE):     1\n")
    ctl.write(" X_start                                        :     282.000\n")
    ctl.write(" X_end                                          :     289.992\n")
    ctl.write(" Y_Start                                        :     -50.0\n")
    ctl.write(" Y_end                                          :     -34.0088\n")
    ctl.write(" File Name of Bathymetry Data                   : topo216v2.xyz\n")
    ctl.write(" Data Format Option (0-OLD;1-MOST;2-XYZ;3-ETOPO):     2\n")
    ctl.write(" Grid Identification Number                     :    01\n")
    ctl.write(" Grid Level                                     :     1\n")
    ctl.write(" Parent Grid's ID Number                        :    -1\n")
    ctl.write("\n")
    ctl.write("#===============================================:=============================== \n")
    ctl.write("#  Parameters for Sub-level grid -- layer 02    :Values                        |\n")
    ctl.write("#===============================================:===============================\n")
    if "thno_054_salida.xyz" in lista_nombre_grillas:
        ctl.write(" Run This Layer ?       (0:Yes,       1:No     ):     0\n")
    else:
        ctl.write(" Run This Layer ?       (0:Yes,       1:No     ):     1\n")
    ctl.write(" Coordinate           (0:spherical, 1:cartesian):     0\n")
    ctl.write(" Governing Eqn.       (0:linear,    1:nonlinear):     0\n")
    ctl.write(" Bottom Friction Switch? (0:Yes,1:No,2:var. n ) :     1\n")
    ctl.write(" Manning's Roughness Coef. (For fric.option=0)  :     " + friccion1 + "\n")
    ctl.write(" Layer Ouput Option? (0:Z+Hu+Hv;1:Z Only;2:NONE):     1\n")
    ctl.write(" GridSize Ratio of Parent layer to current layer:     4\n")
    ctl.write(" X_start                                        : 285.976\n")
    ctl.write(" X_end                                          : 288.064\n")
    ctl.write(" Y_start                                        : -37.624\n")
    ctl.write(" Y_end                                          : -36.409\n")
    ctl.write(" FileName of Water depth data                   : thno_054_salida.xyz\n")
    ctl.write(" Data Format Option (0-OLD;1-MOST;2-XYZ;3-ETOPO):     2\n")
    ctl.write(" Grid Identification Number                     :    02\n")
    ctl.write(" Grid Level                                     :     2\n")
    ctl.write(" Parent Grid's ID Number                        :    01\n")
    ctl.write("\n")
    ctl.write("#===============================================:=============================== \n")
    ctl.write("#  Parameters for Sub-level grid -- layer 03    :Values                        |\n")
    ctl.write("#===============================================:===============================\n")
    if "talcahuano3_salida_nuevo.xyz" in lista_nombre_grillas:
        ctl.write(" Run This Layer ?       (0:Yes,       1:No     ):     0\n")
    else:
        ctl.write(" Run This Layer ?       (0:Yes,       1:No     ):     1\n")
    ctl.write(" Coordinate           (0:spherical, 1:cartesian):     0\n")
    ctl.write(" Governing Eqn.       (0:linear,    1:nonlinear):     1\n")
    ctl.write(" Bottom Friction Switch? (0:Yes,1:No,2:var. n ) :     1\n")
    ctl.write(" Manning's Roughness Coef. (For fric.option=0)  :     " + friccion1 + "\n")
    ctl.write(" Layer Ouput Option? (0:Z+Hu+Hv;1:Z Only;2:NONE):     1\n")
    ctl.write(" GridSize Ratio of Parent layer to current layer:     5\n")
    ctl.write(" X_start                                        :  286.7418\n")
    ctl.write(" X_end                                          :  287.0676\n")
    ctl.write(" Y_start                                        :  -36.792\n")
    ctl.write(" Y_end                                          :  -36.5364\n")
    ctl.write(" FileName of Water depth data                   : talcahuano3_salida_nuevo.xyz\n")
    ctl.write(" Data Format Option (0-OLD;1-MOST;2-XYZ;3-ETOPO):     2 \n")
    ctl.write(" Grid Identification Number                     :    03\n")
    ctl.write(" Grid Level                                     :     3\n")
    ctl.write(" Parent Grid's ID Number                        :    02 \n")
    ctl.write(" \n")
    ctl.write("#===============================================:=============================== \n")
    ctl.write("#  Parameters for Sub-level grid -- layer 04    :Values                        |\n")
    ctl.write("#===============================================:===============================\n")
    if "thnog4_salida.xyz" in lista_nombre_grillas:
        ctl.write(" Run This Layer ?       (0:Yes,       1:No     ):     0\n")
    else:
        ctl.write(" Run This Layer ?       (0:Yes,       1:No     ):     1\n")
    ctl.write(" Coordinate           (0:spherical, 1:cartesian):     0\n")
    ctl.write(" Governing Eqn.       (0:linear,    1:nonlinear):     1\n")
    ctl.write(" Bottom Friction Switch? (0:Yes,1:No,2:var. n ) :     0\n")
    ctl.write(" Manning's Roughness Coef. (For fric.option=0)  :     " + friccion2 + "\n")
    ctl.write(" Layer Ouput Option? (0:Z+Hu+Hv;1:Z Only;2:NONE):     1\n")
    ctl.write(" GridSize Ratio of Parent layer to current layer:     6\n")
    ctl.write(" X_start                                        :    286.86055\n")
    ctl.write(" X_end                                          :    287.05825\n")
    ctl.write(" Y_start                                        :    -36.74905\n")
    ctl.write(" Y_end                                          :    -36.59275\n")
    ctl.write(" FileName of Water depth data                   : thnog4_salida.xyz\n")
    ctl.write(" Data Format Option (0-OLD;1-MOST;2-XYZ;3-ETOPO):     2\n")
    ctl.write(" Grid Identification Number                     :    04\n")
    ctl.write(" Grid Level                                     :     4\n")
    ctl.write(" Parent Grid's ID number                        :    03 \n")
    ctl.write(" \n")
    ctl.write("#===============================================:=============================== \n")
    ctl.write("#  Parameters for Sub-level grid -- layer 05    :Values                        |\n")
    ctl.write("#===============================================:===============================\n")
    if "corral_054_salida.xyz" in lista_nombre_grillas:
        ctl.write(" Run This Layer ?       (0:Yes,       1:No     ):     0\n")
    else:
        ctl.write(" Run This Layer ?       (0:Yes,       1:No     ):     1\n")
    ctl.write(" Coordinate           (0:spherical, 1:cartesian):     0\n")
    ctl.write(" Governing Eqn.       (0:linear,    1:nonlinear):     0\n")
    ctl.write(" Bottom Friction Switch? (0:Yes,1:No,2:var. n ) :     1\n")
    ctl.write(" Manning's Roughness Coef. (For fric.option=0)  :     " + friccion1 + "\n")
    ctl.write(" Layer Ouput Option? (0:Z+Hu+Hv;1:Z Only;2:NONE):     1\n")
    ctl.write(" GridSize Ratio of Parent layer to current layer:     4\n")
    ctl.write(" X_start                                        :    285.616\n")
    ctl.write(" X_end                                          :    287.416\n")
    ctl.write(" Y_start                                        :    -40.612\n")
    ctl.write(" Y_end                                          :    -39.1\n")
    ctl.write(" FileName of Water depth data                   : corral_054_salida.xyz\n")
    ctl.write(" Data Format Option (0-OLD;1-MOST;2-XYZ;3-ETOPO):     2\n")
    ctl.write(" Grid Identification Number                     :    05\n")
    ctl.write(" Grid Level                                     :     2\n")
    ctl.write(" Parent Grid's ID number                        :    01 \n")
    ctl.write(" \n")
    ctl.write("#===============================================:=============================== \n")
    ctl.write("#  Parameters for Sub-level grid -- layer 06    :Values                        |\n")
    ctl.write("#===============================================:===============================\n")
    if "corral3_salida.xyz" in lista_nombre_grillas:
        ctl.write(" Run This Layer ?       (0:Yes,       1:No     ):     0\n")
    else:
        ctl.write(" Run This Layer ?       (0:Yes,       1:No     ):     1\n")
    ctl.write(" Coordinate           (0:spherical, 1:cartesian):     0\n")
    ctl.write(" Governing Eqn.       (0:linear,    1:nonlinear):     1\n")
    ctl.write(" Bottom Friction Switch? (0:Yes,1:No,2:var. n ) :     1\n")
    ctl.write(" Manning's Roughness Coef. (For fric.option=0)  :     " + friccion1 + "\n")
    ctl.write(" Layer Ouput Option? (0:Z+Hu+Hv;1:Z Only;2:NONE):     1\n")
    ctl.write(" GridSize Ratio of Parent layer to current layer:     5\n")
    ctl.write(" X_start                                        :   286.53333\n")
    ctl.write(" X_end                                          :   286.65833\n")
    ctl.write(" Y_start                                        :   -39.95\n")
    ctl.write(" Y_end                                          :   -39.8\n")
    ctl.write(" FileName of Water depth data                   : corral3_salida.xyz\n")
    ctl.write(" Data Format Option (0-OLD;1-MOST;2-XYZ;3-ETOPO):     2\n")
    ctl.write(" Grid Identification Number                     :    06\n")
    ctl.write(" Grid Level                                     :     3\n")
    ctl.write(" Parent Grid's ID number                        :    05\n")
    ctl.write(" \n")
    ctl.write("#===============================================:=============================== \n")
    ctl.write("#  Parameters for Sub-level grid -- layer 07    :Values                        |\n")
    ctl.write("#===============================================:===============================\n")
    if "corral4_salida1.xyz" in lista_nombre_grillas:
        ctl.write(" Run This Layer ?       (0:Yes,       1:No     ):     0\n")
    else:
        ctl.write(" Run This Layer ?       (0:Yes,       1:No     ):     1\n")
    ctl.write(" Coordinate           (0:spherical, 1:cartesian):     0\n")
    ctl.write(" Governing Eqn.       (0:linear,    1:nonlinear):     1\n")
    ctl.write(" Bottom Friction Switch? (0:Yes,1:No,2:var. n ) :     0\n")
    ctl.write(" Manning's Roughness Coef. (For fric.option=0)  :     " + friccion2 + "\n")
    ctl.write(" Layer Ouput Option? (0:Z+Hu+Hv;1:Z Only;2:NONE):     1\n")
    ctl.write(" GridSize Ratio of Parent layer to current layer:     6\n")
    ctl.write(" X_start                                        :   286.5666\n")
    ctl.write(" X_end                                          :   286.5972\n")
    ctl.write(" Y_start                                        :   -39.8937\n")
    ctl.write(" Y_end                                          :   -39.8703\n")
    ctl.write(" FileName of Water depth data                   : corral4_salida1.xyz\n")
    ctl.write(" Data Format Option (0-OLD;1-MOST;2-XYZ;3-ETOPO):     2\n")
    ctl.write(" Grid Identification Number                     :    07\n")
    ctl.write(" Grid Level                                     :     4\n")
    ctl.write(" Parent Grid's ID number                        :    06 \n")
    ctl.write("\n")
    ctl.write("#===============================================:=============================== \n")
    ctl.write("#  Parameters for Sub-level grid -- layer 08    :Values                        |\n")
    ctl.write("#===============================================:===============================\n")
    if "ancud_054_salida.xyz" in lista_nombre_grillas:
        ctl.write(" Run This Layer ?       (0:Yes,       1:No     ):     0\n")
    else:
        ctl.write(" Run This Layer ?       (0:Yes,       1:No     ):     1\n")
    ctl.write(" Coordinate           (0:spherical, 1:cartesian):     0\n")
    ctl.write(" Governing Eqn.       (0:linear,    1:nonlinear):     0\n")
    ctl.write(" Use Bottom friction ?(only cart,nonlin,0:y,1:n):     1\n")
    ctl.write(" Manning's Roughness Coef. (For fric.option=0)  :     " + friccion1 + "\n")
    ctl.write(" Layer Ouput Option? (0:Z+Hu+Hv;1:Z Only;2:NONE):     1\n")
    ctl.write(" GridSize Ratio of Parent layer to current layer:     4\n")
    ctl.write(" X_start                                        :   285.22\n")
    ctl.write(" X_end                                          :   287.416\n")
    ctl.write(" Y_start                                        :   -42.628\n")
    ctl.write(" Y_end                                          :   -41.008\n")
    ctl.write(" FileName of Water depth data                   : ancud_054_salida.xyz\n")
    ctl.write(" Data Format Option (0-OLD;1-MOST;2-XYZ;3-ETOPO):     2\n")
    ctl.write(" Grid Identification Number                     :    08\n")
    ctl.write(" Grid Level                                     :     2\n")
    ctl.write(" Parent Grid's ID number                        :    01\n")
    ctl.write(" \n")
    ctl.write("#===============================================:=============================== \n")
    ctl.write("#  Parameters for Sub-level grid -- layer 09    :Values                        |\n")
    ctl.write("#===============================================:===============================\n")
    if "ancud3_nueva_salida.xyz" in lista_nombre_grillas:
        ctl.write(" Run This Layer ?       (0:Yes,       1:No     ):     0\n")
    else:
        ctl.write(" Run This Layer ?       (0:Yes,       1:No     ):     1\n")
    ctl.write(" Coordinate           (0:spherical, 1:cartesian):     0\n")
    ctl.write(" Governing Eqn.       (0:linear,    1:nonlinear):     1\n")
    ctl.write(" Bottom Friction Switch? (0:Yes,1:No,2:var. n ) :     1\n")
    ctl.write(" Manning's Roughness Coef. (For fric.option=0)  :     " + friccion1 + "\n")
    ctl.write(" Layer Ouput Option? (0:Z+Hu+Hv;1:Z Only;2:NONE):     1\n")
    ctl.write(" GridSize Ratio of Parent layer to current layer:     5\n")
    ctl.write(" X_start                                        :    285.9948\n")
    ctl.write(" X_end                                          :    286.4628\n")
    ctl.write(" Y_start                                        :    -41.9976\n")
    ctl.write(" Y_end                                          :    -41.6466\n")
    ctl.write(" FileName of Water depth data                   : ancud3_nueva_salida.xyz\n")
    ctl.write(" Data Format Option (0-OLD;1-MOST;2-XYZ;3-ETOPO):     2\n")
    ctl.write(" Grid Identification Number                     :    09\n")
    ctl.write(" Grid Level                                     :     3\n")
    ctl.write(" Parent Grid's ID number                        :    08\n")
    ctl.write(" \n")
    ctl.write("#===============================================:=============================== \n")
    ctl.write("#  Parameters for Sub-level grid -- layer 10    :Values                        |\n")
    ctl.write("#===============================================:===============================\n")
    if "ancud4_salida1.xyz" in lista_nombre_grillas:
        ctl.write(" Run This Layer ?       (0:Yes,       1:No     ):     0\n")
    else:
        ctl.write(" Run This Layer ?       (0:Yes,       1:No     ):     1\n")
    ctl.write(" Coordinate           (0:spherical, 1:cartesian):     0\n")
    ctl.write(" Governing Eqn.       (0:linear,    1:nonlinear):     1\n")
    ctl.write(" Bottom Friction Switch? (0:Yes,1:No,2:var. n ) :     0\n")
    ctl.write(" Manning's Roughness Coef. (For fric.option=0)  :     " + friccion2 + "\n")
    ctl.write(" Layer Ouput Option? (0:Z+Hu+Hv;1:Z Only;2:NONE):     1\n")
    ctl.write(" GridSize Ratio of Parent layer to current layer:     6\n")
    ctl.write(" X_start                                        :   286.104\n")
    ctl.write(" X_end                                          :   286.203\n")
    ctl.write(" Y_start                                        :   -41.8953\n")
    ctl.write(" Y_end                                          :   -41.8341\n")
    ctl.write(" FileName of Water depth data                   : ancud4_salida1.xyz\n")
    ctl.write(" Data Format Option (0-OLD;1-MOST;2-XYZ;3-ETOPO):     2\n")
    ctl.write(" Grid Identification Number                     :    10\n")
    ctl.write(" Grid Level                                     :     4\n")
    ctl.write(" Parent Grid's ID number                        :    09\n")
    ctl.write(" \n")
    ctl.write("#===============================================:=============================== \n")
    ctl.write("#  Parameters for Sub-level grid -- layer 11    :Values                        |\n")
    ctl.write("#===============================================:===============================\n")
    ctl.write(" Run This Layer ?       (0:Yes,       1:No     ):     1\n")
    ctl.write(" Coordinate           (0:spherical, 1:cartesian):     1\n")
    ctl.write(" Governing Eqn.       (0:linear,    1:nonlinear):     1\n")
    ctl.write(" Bottom Friction Switch? (0:Yes,1:No,2:var. n ) :     1\n")
    ctl.write(" Manning's Roughness Coef. (For fric.option=0)  :     0.013\n")
    ctl.write(" Layer Ouput Option? (0:Z+Hu+Hv;1:Z Only;2:NONE):     1\n")
    ctl.write(" GridSize Ratio of Parent layer to current layer:     5\n")
    ctl.write(" X_start                                        :   858.\n")
    ctl.write(" X_end                                          :   968.\n")
    ctl.write(" Y_start                                        :   246.\n")
    ctl.write(" Y_end                                          :   388.\n")
    ctl.write(" FileName of Water depth data                   : layer42.dep\n")
    ctl.write(" Data Format Option (0-OLD;1-MOST;2-XYZ;3-ETOPO):     0 \n")
    ctl.write(" Grid Identification Number                     :    11\n")
    ctl.write(" Grid Level                                     :     2\n")
    ctl.write(" Parent Grid's ID number                        :    01\n")
    ctl.write(" \n")
    ctl.write("#===============================================:=============================== \n")
    ctl.write("#  Parameters for Sub-level grid -- layer 12    :Values                        |\n")
    ctl.write("#===============================================:===============================\n")
    ctl.write(" Run This Layer ?       (0:Yes,       1:No     ):     1\n")
    ctl.write(" Coordinate           (0:spherical, 1:cartesian):     1\n")
    ctl.write(" Governing Eqn.       (0:linear,    1:nonlinear):     1\n")
    ctl.write(" Bottom Friction Switch? (0:Yes,1:No,2:var. n ) :     1\n")
    ctl.write(" Manning's Roughness Coef. (For fric.option=0)  :     0.013\n")
    ctl.write(" Layer Ouput Option? (0:Z+Hu+Hv;1:Z Only;2:NONE):     1\n")
    ctl.write(" GridSize Ratio of Parent layer to current layer:     5\n")
    ctl.write(" X_start                                        :  2154.\n")
    ctl.write(" X_end                                          :  2258.\n")
    ctl.write(" Y_start                                        :   671.\n")
    ctl.write(" Y_end                                          :   825.\n")
    ctl.write(" FileName of Water depth data                   : layer43.dep\n")
    ctl.write(" Data Format Option (0-OLD;1-MOST;2-XYZ;3-ETOPO):     0 \n")
    ctl.write(" Grid Identification Number                     :    12\n")
    ctl.write(" Grid Level                                     :     2\n")
    ctl.write(" Parent Grid's ID number                        :    01\n")
    ctl.write(" \n")
    ctl.write("#===============================================:=============================== \n")
    ctl.write("#  Parameters for Sub-level grid -- layer 13    :Values                        |\n")
    ctl.write("#===============================================:===============================\n")
    ctl.write(" Run This Layer ?       (0:Yes,       1:No     ):     1\n")
    ctl.write(" Coordinate           (0:spherical, 1:cartesian):     1\n")
    ctl.write(" Governing Eqn.       (0:linear,    1:nonlinear):     0\n")
    ctl.write(" Bottom Friction Switch? (0:Yes,1:No,2:var. n ) :     1\n")
    ctl.write(" Manning's Roughness Coef. (For fric.option=0)  :     0.013\n")
    ctl.write(" Layer Ouput Option? (0:Z+Hu+Hv;1:Z Only;2:NONE):     1\n")
    ctl.write(" GridSize Ratio of Parent layer to current layer:     5\n")
    ctl.write(" X_start                                        :    41.\n")
    ctl.write(" X_end                                          :    60.\n")
    ctl.write(" Y_start                                        :    41.\n")
    ctl.write(" Y_end                                          :    60.\n")
    ctl.write(" FileName of Water depth data                   : layer44.dep\n")
    ctl.write(" Data Format Option (0-OLD;1-MOST;2-XYZ;3-ETOPO):     0 \n")
    ctl.write(" Grid Identification Number                     :    13\n")
    ctl.write(" Grid Level                                     :     2\n")
    ctl.write(" Parent Grid's ID number                        :    01\n")
    ctl.write(" \n")

    ctl.close()
 

